## Numpy

Earlier we have a lot of mathmatical functions inside the matlab but there is no such good mathmatical packages inside the python, so researchers has developed a best mathmatical package inside the python and named it as a "Numpy"

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. **NumPy was created in 2005 by Travis Oliphant.** It is an open source project and you can use it freely. **NumPy stands for Numerical Python.**

In [1]:
#import numpy library
import numpy as np # np is the aliasing name

In [2]:
#Converting list into an array
l=[11,22,33,44,55] # This is the list

arr=np.array(l) # we are doing type casting from list to array using numpy library

In [3]:
print(arr)

[11 22 33 44 55]


In [4]:
type(arr) # It will give the answer as "numpy.ndarray" , nd means 'n' dimension

numpy.ndarray

In [5]:
# we can also use asarray function to typecast list into array

arr1=np.asarray(l)
print(type(arr1))

<class 'numpy.ndarray'>


**what is the mean of dimensions?**

1 dimension --> It has only one row , 
'n' dimension --> It has multiple rows and columns

dimension can be found using : array.ndim

In [6]:
# 1 dimension array ( 1D array)

one_d_array=np.array([11,22,33,44,55,66])

# Dimension of above array
print("Dimension of 1 D array:",one_d_array.ndim)

# length of 1 D array

print("Length of 1 D array:",len(one_d_array)) # it will give the count of all the elements

# 2 dimension array

two_d_array= np.array([[11,22,33],[44,55,66]]) #2D array starts with 2 square brackets "[[" and end with "]]"
print(two_d_array)
print("Length of 2 D array:",len(two_d_array)) # It will provide the count of number of rows

print("Dimension 2D array:",two_d_array.ndim)

# 3 dimension array

three_d_array=np.array([[[1,2,3],[4,5,6]]])

print("Dimension 3D array:",three_d_array.ndim)
print("Length of 3D array:",len(three_d_array))

Dimension of 1 D array: 1
Length of 1 D array: 6
[[11 22 33]
 [44 55 66]]
Length of 2 D array: 2
Dimension 2D array: 2
Dimension 3D array: 3
Length of 3D array: 1


In [7]:
print(type(two_d_array))

<class 'numpy.ndarray'>


In [8]:
# To know the dimension of the array

print(two_d_array.ndim) 

2


In [9]:
# For the above 2D array we have 2 rows and 3 columns, every row index and column index starts with '0'

print(two_d_array[0][1])

22


In [10]:
print(two_d_array[1][0])

44


In [11]:
print(two_d_array)

[[11 22 33]
 [44 55 66]]


In [12]:
#To access all the elements inside the array, we can use for loop.

for i in range(0,len(two_d_array)): # len(two_d_array) is 2 
    for j in range(0,len(two_d_array[i])):
        print(i,"th row",j,"th column element is:",two_d_array[i][j])

0 th row 0 th column element is: 11
0 th row 1 th column element is: 22
0 th row 2 th column element is: 33
1 th row 0 th column element is: 44
1 th row 1 th column element is: 55
1 th row 2 th column element is: 66


In [13]:
# Number of elements in an array found using array.size

arr= np.array([[11,22,33,44],[55,66,77,88]])

print("Size of array:",arr.size)

one_d_arr=np.array([11,22,33,44])

print("Size of array:",one_d_arr.size)

Size of array: 8
Size of array: 4


In [14]:
# Finding the shape of array( number of rows and columns)

arr= np.array([[11,22,33,44],[55,66,77,88]])

print("shape of arr:",arr.shape) # as it is 2 d array it will return the rows and columns
 
one_d_arr=np.array([11,22,33,44])

print("shape of one_d_arr:",one_d_arr.shape) # as it is 1 d array it have only row no column

shape of arr: (2, 4)
shape of one_d_arr: (4,)


In [15]:
# finding datatypes

arr= np.array([[11,22,33,44],[55,66,77,88]])

print("datatype of arr:",arr.dtype) # datatype of array used in the arr
 
one_d_arr=np.array([11.0,22.0,33.0,44.0])
print("datatype of one_d_arr:",one_d_arr.dtype) # datatype of array used in the one_d_arr

datatype of arr: int32
datatype of one_d_arr: float64


In [16]:
# Generating the array with the specified range

print(np.arange(0,20)) #[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

print(np.arange(0,20,2)) # [ 0  2  4  6  8 10 12 14 16 18]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
# Difference between arrays and matrices

# The dimensions of array can be anything but the matrices dimension will be start from 2 only

l=[1,2,3,4,5]

# type cast the above list into array and find the dimension

arr=np.array(l)
print("Array:",arr)

print("dimension of array:",arr.ndim)

# typecast the above list l into matrice and find the dimension

mat= np.matrix(l)

print("matrix:",mat)
print("Dimension of matrix:",mat.ndim) # It will give you the 2

Array: [1 2 3 4 5]
dimension of array: 1
matrix: [[1 2 3 4 5]]
Dimension of matrix: 2


The numpy. asanyarray() function is used to convert a given input to an ndarray, **but pass ndarray subclasses through.** Input data, in any form that can be converted to an array. This includes scalars, lists, lists of tuples, tuples, tuples of tuples, tuples of lists, and ndarrays.

In [18]:
## Example to understand asanarray() function

l=[9,8,7,5,10]

a=10

## asanarray() function will convert any form of data into array

arr= np.asanyarray(l)

arr1=np.asanyarray(a)

print("arr:",arr,"type of arr:",type(arr))
print("arr1:",arr1,"type of arr1",type(arr1)) # As you can observe the type of arr1 is also changed to array

# But if the input which we are passing to asanarray() is subclass of array module like "matrix" then asanarray() 
# function won't convert the matrix into array

mat= np.matrix(l) # this is matrix

print("Type of mat:",type(mat)) # <class 'numpy.matrix'>

# Let's use asanarray() function on above matrix

arr3=np.asanyarray(mat)

print("type of arr3:",type(arr3)) # <class 'numpy.matrix'>

## As you can observe in the output the type of the arr3 still remains as matrix as the matrix is subclass of arrays so
# np.asanarray won't change it to an array

arr: [ 9  8  7  5 10] type of arr: <class 'numpy.ndarray'>
arr1: 10 type of arr1 <class 'numpy.ndarray'>
Type of mat: <class 'numpy.matrix'>
type of arr3: <class 'numpy.matrix'>


In [19]:
# Shallow copy

arr= np.array([11,22,33,44,55,66])

a=arr # Shallow copying the arr with a

# Let's make a change in the arr 

arr[0]=1000 # As we used the shallow copy, if we change the content in arr or a the content in a or arr will also change.

print("Content in arr:",arr) # [1000   22   33   44   55   66]
print("Content in a:",a) # [1000   22   33   44   55   66] , the content in a also changed as we used shallow copy

print()
print("shallow copy in the sense 'a' is the reference to the 'arr', both 'a' and 'arr' points to the same memory location, so  if we change the content in one array ('a' or 'arr') then automatically the content in another array will updated as we used shallow copy.")

# shallow copy in the sense 'a' is the reference to the 'arr', both 'a' and 'arr' points to the same mempry location, so 
# if we chnage the content in one array ('a' or 'arr') then automatically the content in another array will updated as we used
# shallow copy.

# In this example we can say a is the reference to the 'arr'

Content in arr: [1000   22   33   44   55   66]
Content in a: [1000   22   33   44   55   66]

shallow copy in the sense 'a' is the reference to the 'arr', both 'a' and 'arr' points to the same memory location, so  if we change the content in one array ('a' or 'arr') then automatically the content in another array will updated as we used shallow copy.


In [20]:
# Deep copy

arr=np.array([23,24,25,26])

b=np.copy(arr) # here we used deep copy that means both arr and b will point out to differemt memory locations (not to the same one)
# b=arr.copy() # we can use this one as well.
arr[0]=999

print("Content of arr:",arr) #[999  24  25  26]
print("Content of b:",b) # [23 24 25 26]

# As we used the deep copy, the change in content of one object is not affected the content in another object. As the both objects 
#  point to the different memory location, the changes wont occur.

Content of arr: [999  24  25  26]
Content of b: [23 24 25 26]


In [21]:
np.fromfunction(lambda i,j: i+j ,(3,3)) 

# fromfunction is used to generate the dataset using the function and provided shape

# np.fromfunction(func, (row,column))

# here we have provided 3 row and 3 column that means i starts with 0 to 2 and j starts with 0 to 2 
#     0  1  2 
#  0[ a  b  c]
#  1[ d  e  f]
#  2[ g  h  i]

# [0+0  0+1  0+2]
# [1+0  1+1  1+2]
# [2+0  2+1  2+2]      i,e [ row index+ column index]

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [22]:
np.fromfunction(lambda i,j: i==j ,(3,3)) 

# fromfunction is used to generate the array using the function and provided shape

# np.fromfunction(func, (row,column))

# here we have provided 3 row and 3 column that means i starts with 0 to 2 and j starts with 0 to 2 
#     0  1  2 
#  0[ a  b  c]
#  1[ d  e  f]
#  2[ g  h  i]

# [0==0  0==1  0==2]
# [1==0  1==1  1==2]
# [2==0  2==1  2==2]      i,e [ row index==column index]

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j: i*j ,(3,3)) 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
# As we know, we can generate the numbers using generator as below and we can extract those data using list:

(i**i for i in range(0,5)) # It is an generator object 

# Using list to extract the data which was generated by generator

data= list((i**i for i in range(0,5)))

print("Data extracted using list:",data)

# How can we do the above operation using the numpy library

iterable =(i**i for i in range(0,5))

print("Data extracted from generator using numpy library:",np.fromiter(iterable,int))
# print("Data extracted from generator using numpy library as float data type:",np.fromiter(iterable,float))

# np.fromiter(iterable,int) --> you can place 'float' in place of int, it will show the data in that way

Data extracted using list: [1, 1, 4, 27, 256]
Data extracted from generator using numpy library: [  1   1   4  27 256]


In [25]:
# Generating list from the string

print(np.fromstring("11 22 33 44 55", sep=" "))

print(np.fromstring("11,22,33,44,55",sep=","))

[11. 22. 33. 44. 55.]
[11. 22. 33. 44. 55.]
