In [1]:
import numpy as np

In [2]:
# Sorting, searching and counting functions

#sort 

arr=np.array([22,11,10,25,32,47,1])

print(np.sort(arr))

#or

print(arr)

arr.sort() # It won't return any value, it sort the array in the background.

print(arr)

[ 1 10 11 22 25 32 47]
[22 11 10 25 32 47  1]
[ 1 10 11 22 25 32 47]


In [3]:
#sorting along the axes

arr= np.array([[11,34,2,1,6],[22,4,2,88,45],[230,4,1,67,89]])

print(arr)

# [[ 11  34   2   1   6]
#  [ 22   4   2  88  45]
#  [230   4   1  67  89]]

print(np.sort(arr,axis=0)) # axis=0--> first element, 2nd element, 3rd element of evey row will be considered and sorted

# [[ 11   4   1   1   6]
#  [ 22   4   2  67  45]
#  [230  34   2  88  89]]

print(np.sort(arr,axis=1)) # axis=1-->  first element, 2nd element, 3rd element of evey column will be considered and sorted

# [[  1   2   6  11  34]
#  [  2   4  22  45  88]
#  [  1   4  67  89 230]]

[[ 11  34   2   1   6]
 [ 22   4   2  88  45]
 [230   4   1  67  89]]
[[ 11   4   1   1   6]
 [ 22   4   2  67  45]
 [230  34   2  88  89]]
[[  1   2   6  11  34]
 [  2   4  22  45  88]
 [  1   4  67  89 230]]


In [4]:
# searchsorted

# Find indices where elements should be inserted to maintain order.

# Find the indices into a sorted array `a` such that, if the
# corresponding elements in `v` were inserted before the indices, the
# order of `a` would be preserved.

arr=np.array([3,4,5,10,1,2,3,3])

print(np.searchsorted(arr,6))

# search sorted function will find indices where elements should be inserted to maintain order.

# In above example, if we sort the arr --> 1,2,3,3,3,4,5,10 --> so maintain the order we must place '6' at 8th position (not index)

arr=np.array([1,10,3,5,2,66,77])

print(np.searchsorted(arr,30))

# In above example, if we sort the arr --> 1,2,3,5,10,66,77 --> so maintain the order we must place '30' at 5th position (index)


8
5


In [5]:
# Count function

# Counts the number of non-zero values in the array ``a``.

arr=np.array([1,2,4,3,5,10,11,12,13,0,0,4,5,2,4,0])

print(np.count_nonzero(arr)) # There are currently 13 non-zero elements present in the above array

# count function with axes

arr= np.array([[11,22,0,0],[0,0,33,45],[23,0,0,45]])

print(arr)

# [[11 22  0  0]
#  [ 0  0 33 45]
#  [23  0  0 45]]

print(np.count_nonzero(arr,axis=0)) # axis=0 ,  first element, 2nd element, 3rd element of every row will be considered

# [2 1 1 2]

print(np.count_nonzero(arr,axis=1)) # axis=1,  first element, 2nd element, 3rd element of every column will be considered 

# [2 2 2]

13
[[11 22  0  0]
 [ 0  0 33 45]
 [23  0  0 45]]
[2 1 1 2]
[2 2 2]


In [6]:
# where

# where(condition, [x, y], /)

# Return elements chosen from `x` or `y` depending on `condition`.

# Return the indices of the elements based on the condition.

arr=np.array([1,2,4,3,5,10,11,12,13,0,0,4,5,2,4,0,23,45,67])

print(np.where(arr>5))

# (array([ 5,  6,  7,  8, 16, 17, 18], dtype=int64),)

print(arr[np.where(arr>5)]) # It will print the all the return elements based on the condition.

# [10 11 12 13 23 45 67]

# working on 2D array

arr1= np.array([[11,22,0,0],[0,0,33,45],[23,0,0,45]])

print(np.where(arr1>20))

# (array([0, 1, 1, 2, 2], dtype=int64), array([1, 2, 3, 0, 3], dtype=int64))

# for 2d arrays, It will provide two arrays as output, first array represents the row index value and second array 
# represents column index value.

# (array([0, 1, 1, 2, 2], dtype=int64), array([1, 2, 3, 0, 3], dtype=int64))

# 0th row and 1st column , 1st row and 2nd column , 1st row and 3rd column, 2nd row 0th index, 2nd row 3rd index

print(arr1[np.where(arr1>20)])

# [22 33 45 23 45]

(array([ 5,  6,  7,  8, 16, 17, 18], dtype=int64),)
[10 11 12 13 23 45 67]
(array([0, 1, 1, 2, 2], dtype=int64), array([1, 2, 3, 0, 3], dtype=int64))
[22 33 45 23 45]


In [7]:
# extract

# np.extract(condition, arr)

# Return the elements of an array that satisfy some condition.

# This is equivalent to ``np.compress(ravel(condition), ravel(arr))``.  If
# `condition` is boolean ``np.extract`` is equivalent to ``arr[condition]``.

arr=np.array([1,2,4,3,5,10,11,12,6,13,0,0,4,5,2,4,0,23,45,67])

print(np.extract(arr>5,arr)) # it will extract the element which satisfies the provided condition

# [10 11 12  6 13 23 45 67]

print(np.extract(arr,arr>5)) # it will give you whether the element statisfied the given condition or not

# [False False False False False  True  True  True  True  True False False
#  False False  True  True  True]

[10 11 12  6 13 23 45 67]
[False False False False False  True  True  True  True  True False False
 False False  True  True  True]


In [8]:
# Numpy - Byte Swapping [we won't use this in data science]

arr=np.array([10,11,12,13,14])

print(arr.byteswap()) # Represent the byte data for the given elements

print("Before:",arr)

print(arr.byteswap(inplace=True)) # If you make inplace as true, then the data in arr will be replaced by bytes data

print("After:",arr)

[167772160 184549376 201326592 218103808 234881024]
Before: [10 11 12 13 14]
[167772160 184549376 201326592 218103808 234881024]
After: [167772160 184549376 201326592 218103808 234881024]


In [9]:
# Copy and views ( same as deep copy (Copy) and shallow copy(View))

arr=np.array([1,2,3,4,5])

arr1=arr.copy() # Deep copy

# deep copy means if you modify the content in arr it won't affect the content in the arr1, that means both arrays points to 
# different memory locations.

arr[0]=1000

print(arr)

print()

print(arr1)

#****************************************************************************************

arr=np.array([1,2,3,4,5])

a=arr # shallow copy

# here both a and arr points to the same memory location, because of that reason , if we modify the content in any one array 
# then another array will also affected with that change

print(arr)
print(a)

a[0]=999

print(arr)
print(a)

[1000    2    3    4    5]

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[999   2   3   4   5]
[999   2   3   4   5]


In [10]:
# Copy and view 

#Copy (similar to deep copy)

arr=np.array([1,2,3,4])

arr1=np.copy(arr) # same as arr.copy()

# Copy means if you modify the content in arr it won't affect the content in the arr1, that means both arrays points to 
# different memory locations.

print("Before:",arr)
print("Before:",arr1)

arr1[0]=56

print("After:",arr)
print("After:",arr1)

#view (same as shallow copy operation)

arr2=np.array([11,22,33,44])
arr3=arr2.view()

print("before:",arr2)
print("before:",arr3)

arr3[0]=899

print("after:",arr2)
print("after:",arr3)

Before: [1 2 3 4]
Before: [1 2 3 4]
After: [1 2 3 4]
After: [56  2  3  4]
before: [11 22 33 44]
before: [11 22 33 44]
after: [899  22  33  44]
after: [899  22  33  44]


In [11]:
# Copy and view 

#Copy (same as deep copy)

arr=np.array([1,2,3,4])

arr1=np.copy(arr) # same as arr.copy()

# Copy means if you modify the content in arr it won't affect the content in the arr1, that means both arrays points to 
# different memory locations.

print("Before:",arr)
print("Before:",arr1)

arr1[0]=56

print("After:",arr)
print("After:",arr1)

#view (same as shallow copy operation)

arr2=np.array([11,22,33,44])
arr3=arr2.view()

print("before:",arr2)
print("before:",arr3)

arr3[0]=899

print("after:",arr2)
print("after:",arr3)

Before: [1 2 3 4]
Before: [1 2 3 4]
After: [1 2 3 4]
After: [56  2  3  4]
before: [11 22 33 44]
before: [11 22 33 44]
after: [899  22  33  44]
after: [899  22  33  44]


In [12]:
# Numpy matrix ( same as array but here the type is matrix)

import numpy.matlib as matrix # this matlib library has all the functions what array have like np.eye, np.identity, np.zeros etc.,

In [13]:
print(matrix.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
type(matrix.zeros((3,3)))

numpy.matrix

In [15]:
matrix.eye(3,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [16]:
matrix.identity((6))

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [17]:
matrix.ones((3,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
# Linear algebra

# arr1=np.random.randint(1,5,(4,5))
# arr2=np.random.randint(1,5,(4,5))

#or
arr1=np.random.randint([[1,3],[4,6]]) # It will generate the array same as [[1,3],[4,6]] but with diff elements

arr2=np.random.randint([[1,3],[4,6]])

In [19]:
print("arr1:\n",arr1)
print()
print("arr2:\n",arr2)

arr1:
 [[0 0]
 [2 4]]

arr2:
 [[0 1]
 [0 5]]


In [20]:
print(np.dot(arr1,arr2)) # dot product

[[ 0  0]
 [ 0 22]]


In [21]:
arr1@arr2 # dot product max same as matrix multiplication

array([[ 0,  0],
       [ 0, 22]])

In [22]:
# will preapre another notebook for linear algebra for all the functions