In [1]:
import numpy as np

In [2]:
# array manipulation

arr= np.random.randint(1,10,(4,4))

print("Array:\n",arr)

Array:
 [[9 6 7 1]
 [4 4 8 6]
 [5 5 3 9]
 [2 7 4 5]]


In [3]:
# Reshaping

# we need to match the number opf elements always i,e arr has 4*4 =16 elements

arr= np.random.randint(1,10,(4,4))

print("8 row and 2 col:\n",arr.reshape(8,2)) # 8*2 =16 elements --> it is matching with the no.of arr ekements, so it will reshape the arr into 8 row 2 col


print("reshape into 8,2 using -1:\n",arr.reshape(8,-1)) # python automatically take -1 as 2 ( python tries to equal the no..of elements i, e there is one possibility for 8 to make it 16 i,e 2 , so 8*2 --> 8 rows and 2 columns)

8 row and 2 col:
 [[1 8]
 [5 3]
 [5 1]
 [2 8]
 [8 6]
 [5 8]
 [6 4]
 [6 4]]
reshape into 8,2 using -1:
 [[1 8]
 [5 3]
 [5 1]
 [2 8]
 [8 6]
 [5 8]
 [6 4]
 [6 4]]


In [4]:
# Trnasposing ( row become column and column become row)

arr= np.arange(10,40).reshape(5,6)

print(arr)


# Transposing the array

print("Transposing using .T operator:\n",arr.T)

print("Transposing using transpose() function:\n", arr.transpose())

print(arr.T==arr.transpose()) # checking if every element is same or not

print(np.any(arr.T==arr.transpose())) # if all are true then it will return true else will return false.

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]
Transposing using .T operator:
 [[10 16 22 28 34]
 [11 17 23 29 35]
 [12 18 24 30 36]
 [13 19 25 31 37]
 [14 20 26 32 38]
 [15 21 27 33 39]]
Transposing using transpose() function:
 [[10 16 22 28 34]
 [11 17 23 29 35]
 [12 18 24 30 36]
 [13 19 25 31 37]
 [14 20 26 32 38]
 [15 21 27 33 39]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
True


In [5]:
# flatten

arr= np.arange(10,20).reshape(2,5)

print(arr)

# flatten will create 1D array (1 row) with all the elements 

print("flattening the array:\n",arr.flatten())

# ravel 

# ravel will also do the same operation as flatten
# Return a contiguous flattened array.

# A 1-D array, containing the elements of the input, is returned.  A copy is
# made only if needed.

print(np.ravel(arr))

[[10 11 12 13 14]
 [15 16 17 18 19]]
flattening the array:
 [10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]


In [6]:
# expand dimensions

# if you want to increase the dimension of the array say , if you want to convert 1D array to 2D or anything

arr=np.array([1,2,3,4])

print(arr.shape)

print(arr.ndim) # 1 dimension

arr1= np.expand_dims(arr,axis=1)

print("expanded array:\n",arr1)

print(arr1.shape)

print(arr1.ndim)  # expanded the dimension to 2

(4,)
1
expanded array:
 [[1]
 [2]
 [3]
 [4]]
(4, 1)
2


In [7]:
# we can convert 2D array to 3D array as well

arr= np.array([[1,2,3,4],[5,6,7,8]])

print(arr)

print(arr.ndim)

arr1=np.expand_dims(arr,axis=1) # axis=1 represents expand dims column wise 

print(arr1.ndim) # the dimension is increased to 3

print(arr1.shape)

print("arr1:\n",arr1)

arr2=np.expand_dims(arr,axis=0)# axis=0 represents expand dims row wise

print(arr2.ndim) # the dimension is increased to 3

print(arr2.shape)

print("arr2:\n",arr2)

[[1 2 3 4]
 [5 6 7 8]]
2
3
(2, 1, 4)
arr1:
 [[[1 2 3 4]]

 [[5 6 7 8]]]
3
(1, 2, 4)
arr2:
 [[[1 2 3 4]
  [5 6 7 8]]]


In [8]:
arr=np.array([1,2,3,4,5])

print(arr, arr.shape, arr.ndim)

arr1=np.expand_dims(arr,axis=1)# axis=1 represents expand dims column wise

print(arr1, arr1.shape, arr1.ndim)

arr2=np.expand_dims(arr,axis=0) # axis=0 represents expand dims row wise

print(arr2, arr2.shape, arr2.ndim)

[1 2 3 4 5] (5,) 1
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1) 2
[[1 2 3 4 5]] (1, 5) 2


In [9]:
# squeeze

# np.squeeze(a, axis=None)

# It will make the array into 1D array

data=np.array([[1],[2],[3]])

print(np.squeeze(data,axis=1)) # axis=1 , making column array as 1D array 

data=np.array([[1,2,3,4,5,6]])

print(np.squeeze(data,axis=0)) # axis=0,  making row array as 1D array 

[1 2 3]
[1 2 3 4 5 6]


In [10]:
# repeat
# Repeat each element of an array after themselves

data=np.array([[1],[2],[3]])

print(np.repeat(data,2,axis=1)) # repeat the data column wise

# [[1 1]
#  [2 2]
#  [3 3]]

data=np.array([[1],[2],[3]])

print(np.repeat(data,2,axis=0)) # repeat the data row wise

# [[1]
#  [1]
#  [2]
#  [2]
#  [3]
#  [3]]

data=np.array([[1,2,3,4,5,6]])

print(np.repeat(data,2,axis=0))

# [[1 2 3 4 5 6]
#  [1 2 3 4 5 6]]

print(np.repeat(data,4,axis=0))

# [[1 2 3 4 5 6]
#  [1 2 3 4 5 6]
#  [1 2 3 4 5 6]
#  [1 2 3 4 5 6]]

data=np.array([[1,2,3,4,5,6]])

print(np.repeat(data,2,axis=1))

# [[1 1 2 2 3 3 4 4 5 5 6 6]]

[[1 1]
 [2 2]
 [3 3]]
[[1]
 [1]
 [2]
 [2]
 [3]
 [3]]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[[1 1 2 2 3 3 4 4 5 5 6 6]]


In [11]:
# roll

# Roll array elements along a given axis.

# Elements that roll beyond the last position are re-introduced at
# the first.

data=np.array([[11],[22],[33]])

print(np.roll(data,2))

# [[22]
#  [33]
#  [11]]

# Here the data will roll 2 steps. i,e 11 is at 0th position , so after 2 times roll it will be in 2nd position similarly
# 22 is in 1st index and if we roll 2 times then it will be in 1st index , 33 is in 2nd index so after 2 steps it will be in 2nd index

data=np.array([[11,22,33]])

print(np.roll(data,2))

# [[22 33 11]]

# Rolling according to the axis

data= np.array([[11,22,33,44],[55,66,77,88],[99,111,222,333],[444,555,666,777]])

print(data)

# [[ 11  22  33  44]
#  [ 55  66  77  88]
#  [ 99 111 222 333]
#  [444 555 666 777]]

print(np.roll(data,2,axis=0)) # axis=0 represents row

# [[ 99 111 222 333]
#  [444 555 666 777]
#  [ 11  22  33  44]
#  [ 55  66  77  88]]

# as we specified axis=0 , it will concentrate on row data, 1st element of every row [11,55,99,444] , 11 at 0th index so after
# 2 steps the new index will be 2nd index , 55 at 1st index so after 2 steps it will be at 3rd index.

print(np.roll(data,2,axis=1)) # axis=1 represents column wise row

# [[ 33  44  11  22]
#  [ 77  88  55  66]
#  [222 333  99 111]
#  [666 777 444 555]]

# as we specified axis=0, now we need to consider first value of every column and roll the elements to the specified steps (here it is 2)

[[22]
 [33]
 [11]]
[[22 33 11]]
[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 111 222 333]
 [444 555 666 777]]
[[ 99 111 222 333]
 [444 555 666 777]
 [ 11  22  33  44]
 [ 55  66  77  88]]
[[ 33  44  11  22]
 [ 77  88  55  66]
 [222 333  99 111]
 [666 777 444 555]]


In [12]:
# Creating the array with the specified diagonal elements

arr=np.array([11,22,33,44])

print(np.diag(arr))

[[11  0  0  0]
 [ 0 22  0  0]
 [ 0  0 33  0]
 [ 0  0  0 44]]


In [13]:
# Binary Operators (addition, subtraction, multiplication, division, negation)

arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

print("arr1:\n",arr1)

print()

print("arr2:\n",arr2)

arr1:
 [[4 5 8 1]
 [1 7 2 7]
 [1 2 4 2]]

arr2:
 [[5 9 3 7]
 [7 6 6 6]
 [1 6 6 6]]


In [14]:
#addition

print(arr1+arr2)

[[ 9 14 11  8]
 [ 8 13  8 13]
 [ 2  8 10  8]]


In [15]:
# subtraction

print(arr1-arr2)

[[-1 -4  5 -6]
 [-6  1 -4  1]
 [ 0 -4 -2 -4]]


In [16]:
# multiplication

print(arr1*arr2)

# To perform matrix multiplication the column count of first matrix must match with row count of second matrix

[[20 45 24  7]
 [ 7 42 12 42]
 [ 1 12 24 12]]


In [17]:
# division

print(arr1/arr2)

[[0.8        0.55555556 2.66666667 0.14285714]
 [0.14285714 1.16666667 0.33333333 1.16666667]
 [1.         0.33333333 0.66666667 0.33333333]]


In [18]:
#negation (Binary negation)

print(~arr1)

[[-5 -6 -9 -2]
 [-2 -8 -3 -8]
 [-2 -3 -5 -3]]


In [19]:
print(~arr2)

[[ -6 -10  -4  -8]
 [ -8  -7  -7  -7]
 [ -2  -7  -7  -7]]


In [20]:
print(arr1>arr2)

[[False False  True False]
 [False  True False  True]
 [False False False False]]


In [21]:
# Numpy string operations

arr= np.array(['karri',"nethaji","mahendra"])

print(arr)

['karri' 'nethaji' 'mahendra']


In [22]:
# Converting the string data into upper case

print(np.char.upper(arr))

['KARRI' 'NETHAJI' 'MAHENDRA']


In [23]:
# capitalize the data

print(np.char.capitalize(arr))

['Karri' 'Nethaji' 'Mahendra']


In [24]:
# all string functions like title, zfill, isaplha, isalnum etc., are available under np.char

In [25]:
# sin and cosine functions

arr1=np.random.randint(1,10,(3,4))

#sin function

print("Sin data:\n",np.sin(arr1))
print()

# cos function

print("Cos data:\n",np.cos(arr1))
print()



#tan function

print("Tan data:\n",np.tan(arr1))



Sin data:
 [[ 0.6569866   0.14112001  0.14112001  0.90929743]
 [-0.2794155  -0.7568025   0.84147098  0.84147098]
 [ 0.6569866  -0.95892427 -0.7568025   0.90929743]]

Cos data:
 [[ 0.75390225 -0.9899925  -0.9899925  -0.41614684]
 [ 0.96017029 -0.65364362  0.54030231  0.54030231]
 [ 0.75390225  0.28366219 -0.65364362 -0.41614684]]

Tan data:
 [[ 0.87144798 -0.14254654 -0.14254654 -2.18503986]
 [-0.29100619  1.15782128  1.55740772  1.55740772]
 [ 0.87144798 -3.38051501  1.15782128 -2.18503986]]


In [26]:
#log10 --> log to the base 10 function

print(np.log10(arr1))

[[0.84509804 0.47712125 0.47712125 0.30103   ]
 [0.77815125 0.60205999 0.         0.        ]
 [0.84509804 0.69897    0.60205999 0.30103   ]]


In [27]:
# exponential data

print(np.exp(arr1))

[[1096.63315843   20.08553692   20.08553692    7.3890561 ]
 [ 403.42879349   54.59815003    2.71828183    2.71828183]
 [1096.63315843  148.4131591    54.59815003    7.3890561 ]]


In [28]:
# power

print("arr1:\n",arr1)

print(np.power(arr1,2))

arr1:
 [[7 3 3 2]
 [6 4 1 1]
 [7 5 4 2]]
[[49  9  9  4]
 [36 16  1  1]
 [49 25 16  4]]


In [29]:
# mean

arr= np.array([[2,3,4,5],[6,7,8,9]])

print("array:\n",arr)

#  [[2 3 4 5]
#  [6 7 8 9]]

# mean

print(np.mean(arr)) # It will provide the mean for all the elements

#or

print(np.sum(arr)/arr.size)

# if you want to find mean along the axis then

print(np.mean(arr,axis=0)) # axis-0 along with the row

# [4. 5. 6. 7.]

# first element of every row ( 2 rows) is [2 and 6] mean of 2 and 6 is 4. second element of every row is 3 and 7, 
# the mean of 3 and 7 is 5.

print(np.mean(arr,axis=1)) # axis=1 along with the columns

# [3.5 7.5]

# every element from first column 2,3,4,5 --> 2+3+4+5/4 --> 14/4 --> 3.5
# every element from second column 6,7,8,9 --> 6+7+8+9/4 --> 30/4 -->7.5

array:
 [[2 3 4 5]
 [6 7 8 9]]
5.5
5.5
[4. 5. 6. 7.]
[3.5 7.5]


In [30]:
# median

arr= np.array([[2,3,4,5],[6,7,8,9],[10,11,12,13]])

print(arr)

# [[ 2  3  4  5]
#  [ 6  7  8  9]
#  [10 11 12 13]]

print(np.median(arr))

# 7.5

print(np.median(arr,axis=0))

# [6. 7. 8. 9.]

print(np.median(arr,axis=1))

# [ 3.5  7.5 11.5]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
7.5
[6. 7. 8. 9.]
[ 3.5  7.5 11.5]


In [31]:
# modules

arr=np.array([[11,12,14,14],[11,22,22,44],[10,12,10,56]])

print(arr)

# [[11 12 14 14]
#  [11 22 22 44]
#  [10 12 10 56]]

print(np.mod(arr,2)) # every element will be checked as x%2 and in the result array we will get the remainders

# [[1 0 0 0]
#  [1 0 0 0]
#  [0 0 0 0]]

[[11 12 14 14]
 [11 22 22 44]
 [10 12 10 56]]
[[1 0 0 0]
 [1 0 0 0]
 [0 0 0 0]]


In [32]:
# standard deviation

arr= np.array([[2,3,4,5],[6,7,8,9],[10,11,12,13]])

print(arr)

# [[ 2  3  4  5]
#  [ 6  7  8  9]
#  [10 11 12 13]]

print(np.std(arr)) # standard deviation for whole data

# 3.452052529534663

print(np.std(arr,axis=0)) # standard deviation for axis=0 (first element of every row will be considered)

# [3.26598632 3.26598632 3.26598632 3.26598632]

print(np.std(arr,axis=1)) # standard deviation for axis=1 (first element of every column will be considered)

# [1.11803399 1.11803399 1.11803399]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


In [33]:
# variance

arr= np.array([[2,3,4,5],[6,7,8,9],[10,11,12,13]])

print(arr)

# [[ 2  3  4  5]
#  [ 6  7  8  9]
#  [10 11 12 13]]

print(np.var(arr))

# 11.916666666666666

print(np.var(arr,axis=0))

# [10.66666667 10.66666667 10.66666667 10.66666667]

print(np.var(arr,axis=1))

# [1.25 1.25 1.25]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]


In [34]:
# finding max element of array

arr=np.array([[12,33,45],[10,54,90],[2,89,38]])

print(arr)

# [[12 33 45]
#  [10 54 90]
#  [ 2 89 38]]

print(np.max(arr))

#90

print(np.max(arr,axis=0))

# [12 89 90]

print(np.max(arr,axis=1))

# [45 90 89]

[[12 33 45]
 [10 54 90]
 [ 2 89 38]]
90
[12 89 90]
[45 90 89]


In [35]:
# finding min element of array

arr=np.array([[12,33,45],[10,54,90],[2,89,38]])

print(arr)

# [[12 33 45]
#  [10 54 90]
#  [ 2 89 38]]

print(np.min(arr))

# 2

print(np.min(arr,axis=0))

# [ 2 33 38]

print(np.min(arr,axis=1))

# [12 10  2]

[[12 33 45]
 [10 54 90]
 [ 2 89 38]]
2
[ 2 33 38]
[12 10  2]


In [36]:
# Numpy arithmatic operations

arr1= np.random.randint(1,5,(3,3))
arr2= np.random.randint(1,5,(3,3))

# we add the arrays as arr1 and arr2 

print("Addition:\n",arr1+arr2)

# we can do the same operation using numpy package

print("Addition using numpy:\n",np.add(arr1,arr2))

Addition:
 [[5 6 4]
 [4 5 5]
 [5 4 6]]
Addition using numpy:
 [[5 6 4]
 [4 5 5]
 [5 4 6]]


In [37]:
# we can subtract the arrays as arr1-arr2 

print("Subtract:\n",arr1-arr2)

# we can do the same operation using numpy package

print("subtraction using numpy:\n",np.subtract(arr1,arr2))

Subtract:
 [[-1  0  2]
 [ 2 -1 -3]
 [ 3  2 -2]]
subtraction using numpy:
 [[-1  0  2]
 [ 2 -1 -3]
 [ 3  2 -2]]


In [38]:
# we can multiply the arrays as arr1*arr2 

print("Multiply:\n",arr1*arr2)

# we can do the same operation using numpy package

print("Multiplication using numpy:\n",np.multiply(arr1,arr2))

Multiply:
 [[6 9 3]
 [3 6 4]
 [4 3 8]]
Multiplication using numpy:
 [[6 9 3]
 [3 6 4]
 [4 3 8]]


In [39]:
# we can do division of the arrays as arr1/arr2 

print("Division:\n",arr1/arr2)

# we can do the same operation using numpy package

print("Division using numpy:\n",np.divide(arr1,arr2))

Division:
 [[0.66666667 1.         3.        ]
 [3.         0.66666667 0.25      ]
 [4.         3.         0.5       ]]
Division using numpy:
 [[0.66666667 1.         3.        ]
 [3.         0.66666667 0.25      ]
 [4.         3.         0.5       ]]


In [40]:
# we can do modulus of the arrays as arr1%arr2 

print("Modules:\n",arr1%arr2)

# we can do the same operation using numpy package

print("Modules using numpy:\n",np.mod(arr1,arr2))

Modules:
 [[2 0 0]
 [0 2 1]
 [0 0 2]]
Modules using numpy:
 [[2 0 0]
 [0 2 1]
 [0 0 2]]


In [41]:
# we can do power of the arrays as arr1**arr2 

print("Power:\n",arr1**arr2)

# we can do the same operation using numpy package

print("Power using numpy:\n",np.power(arr1,arr2))

Power:
 [[ 8 27  3]
 [ 3  8  1]
 [ 4  3 16]]
Power using numpy:
 [[ 8 27  3]
 [ 3  8  1]
 [ 4  3 16]]
