In [1]:
# importing numpy package
import numpy as np

In [2]:
# Ultra basic

# As we know, array is the collection of homogenous datatype elements

arr=np.array([1,"string",5.6,True,5+3j]) # But here we defined every datatype in the array

# But we know array is collection of same data type element right but here we defined diff diff data type elements.

# Let's try to print the datatype of every element

for i in range(len(arr)):
    print("Element:",arr[i]," data type:",type(arr[i]))
    
# Element: 1  data type: <class 'numpy.str_'>
# Element: string  data type: <class 'numpy.str_'>
# Element: 5.6  data type: <class 'numpy.str_'>
# Element: True  data type: <class 'numpy.str_'>
# Element: (5+3j)  data type: <class 'numpy.str_'>

# As you can observe every element datatype is changed to string.Hence it is satisfied the array definition right (collection of homogenous element)

# OBSERVATION:

# Numpy chnages the datatype of all elements to the lowest common denominator. If there is string, all other element data type 
# will become string datatype.

arr=np.array([1,5.6,True,5+3j]) # string data deleted, then all elements datatype converted to "complex"

for i in range(len(arr)):
    print("Element:",arr[i]," data type:",type(arr[i]))
    
# Element: (1+0j)  data type: <class 'numpy.complex128'>
# Element: (5.6+0j)  data type: <class 'numpy.complex128'>
# Element: (1+0j)  data type: <class 'numpy.complex128'> # boolean data (True) converted to (1+j0)
# Element: (5+3j)  data type: <class 'numpy.complex128'>



# String  ---> Complex --> float --> int --> bool

# Lowest denominator -----------------------> highest denominator

Element: 1  data type: <class 'numpy.str_'>
Element: string  data type: <class 'numpy.str_'>
Element: 5.6  data type: <class 'numpy.str_'>
Element: True  data type: <class 'numpy.str_'>
Element: (5+3j)  data type: <class 'numpy.str_'>
Element: (1+0j)  data type: <class 'numpy.complex128'>
Element: (5.6+0j)  data type: <class 'numpy.complex128'>
Element: (1+0j)  data type: <class 'numpy.complex128'>
Element: (5+3j)  data type: <class 'numpy.complex128'>


In [3]:
# creating 1D array 

arr= np.array([1,2,3,4,5])

# or

# using arange function

arr1= np.arange(0,10)

print(arr)

print(arr1)

# Dimension of array

print("Dimension of arr:",arr.ndim)

# shape of array

print("Shape of arr:",arr.shape) # as it is 1D array it does't have columns

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
Dimension of arr: 1
Shape of arr: (5,)


In [4]:
# Reshaping the array

print( np.arange(0,10).reshape(2,5))

# or

print( np.arange(0,10).reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
# 2D array creation

arr_2= np.array([[11,12,13,14],[15,16,17,18]])

print(arr_2)


# Dimension of array

print("Dimension of arr:",arr_2.ndim)

# shape of array

print("Shape of arr:",arr_2.shape) # as it is 2D array it have columns and rows

[[11 12 13 14]
 [15 16 17 18]]
Dimension of arr: 2
Shape of arr: (2, 4)


In [6]:
# indexing

arr= np.random.randint(1,10,(4,4))

In [7]:
print(arr)

[[7 6 5 4]
 [1 1 5 8]
 [5 2 5 1]
 [3 5 6 4]]


In [8]:
print(arr[0:2,0:2])# it will fetch the row 0,1 and column 0,1 (2 is excluded)

[[7 6]
 [1 1]]


In [9]:
print(arr[0:4:2,0:2]) # 0:4:2 --> 2 represents the step size

[[7 6]
 [5 2]]


In [10]:
print(arr[0:3,0:4:2])

[[7 5]
 [1 5]
 [5 5]]


In [11]:
#arange

print(np.arange(0,10))

print(np.arange(0,10,2)) # 2 represents step size

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [12]:
#linspace

print(np.linspace(0,10)) # by default the data from 0 to 10 will divided to 50 equal parts, if you want to divide into 5 equal parts then

# [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
#   1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
#   2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
#   3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
#   4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
#   6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
#   7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
#   8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
#   9.79591837 10.        ]

print(np.linspace(0,10,5)) # the data from 0 to 10 will be divide into 5 equal parts

# [ 0.   2.5  5.   7.5 10. ]

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 0.   2.5  5.   7.5 10. ]


In [13]:
# array manipulation

arr=np.array([11,22,33,44,55])

print("arr:\n",arr)

arr[2::]=100

print(arr) # changing the content in the array using indexing

arr:
 [11 22 33 44 55]
[ 11  22 100 100 100]


In [14]:
# ones

# Return a new array of given shape and type, filled with ones.

print(np.ones(3))

# [1. 1. 1.]

print(np.ones((3,3)))

# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]

print(np.ones((3,3),dtype=int))

# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
# zeros

# Return a new array of given shape and type, filled with zeros.

print(np.zeros(4))

# [0. 0. 0. 0.]

print(np.zeros((4,4)))

# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

print(np.zeros((4,4),dtype=int))

# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]

print(np.zeros((4,4),dtype=bool))

# [[False False False False]
#  [False False False False]
#  [False False False False]
#  [False False False False]]

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [16]:
# empty 

# Return a new array of given shape and type, without initializing entries.

print(np.empty((2,3)))

print(np.empty(13))

[[0. 0. 0.]
 [0. 0. 0.]]
[1.31491070e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000
 1.01855798e-312 5.19653801e+170 1.77103418e-051 1.36900908e-071
 1.93376641e-076 7.11885357e-038 6.23884563e-042 5.75298863e-066
 6.52306545e-038]


In [17]:
# random

# most used rand function in data science

print(np.random.randint(1,10,4)) # select 4 integers between 1 and 10

print(np.random.randint(1,10,(3,4))) # construct 3x4 array with the integers between 1 and 10

[2 4 2 7]
[[9 1 7 9]
 [6 6 4 4]
 [2 4 8 3]]


In [18]:
# randn

# Return a sample (or samples) from the "standard normal" distribution.

# Highly used in data science statistics, as this is used to generate the sample data from standard normal distribution

print(np.random.randn(2,10))

[[ 1.16643803 -1.81948265  0.1153049  -0.27099331  1.28272171 -0.43575169
  -0.2956361   0.87522568  0.48412926 -0.57437217]
 [-0.24397321 -0.81097844 -0.55015494  0.69203475 -0.19160143  0.43080048
  -0.04039231  0.26840626  1.74593661 -0.19768717]]


In [19]:
# Sorting

arr= np.array([12,15,18,89,34,1,4,2])

print(np.sort(arr))

[ 1  2  4 12 15 18 34 89]


In [20]:
#sorting along the axes

arr= np.array([[11,34,2,1,6],[22,4,2,88,45],[230,4,1,67,89]])

print(arr)

# [[ 11  34   2   1   6]
#  [ 22   4   2  88  45]
#  [230   4   1  67  89]]

print(np.sort(arr,axis=0)) # axis=0--> first element, 2nd element, 3rd element of evey row will be considered and sorted

# [[ 11   4   1   1   6]
#  [ 22   4   2  67  45]
#  [230  34   2  88  89]]

print(np.sort(arr,axis=1)) # axis=1-->  first element, 2nd element, 3rd element of evey column will be considered and sorted

# [[  1   2   6  11  34]
#  [  2   4  22  45  88]
#  [  1   4  67  89 230]]

[[ 11  34   2   1   6]
 [ 22   4   2  88  45]
 [230   4   1  67  89]]
[[ 11   4   1   1   6]
 [ 22   4   2  67  45]
 [230  34   2  88  89]]
[[  1   2   6  11  34]
 [  2   4  22  45  88]
 [  1   4  67  89 230]]


In [21]:
# Concatenate

a= np.array([1,2,3,4])
b=np.array([5,6,7,8])

print(np.concatenate((a,b)))

# [1 2 3 4 5 6 7 8]

print(np.concatenate((a,b),dtype=float))

# [1. 2. 3. 4. 5. 6. 7. 8.]

# 2D arrays

arr1= np.array([[11,22,33,44]])
arr2= np.array([[55,66,77,88]])

print(np.concatenate((arr1,arr2),axis=0)) # axis=0 means concatenate row wise i,e to concatenate the arrays row wise, the count of columns must match

# [[11 22 33 44]
#  [55 66 77 88]]

arr1= np.array([[11,22],[33,44]])
arr2= np.array([[55],[66]])

print(np.concatenate((arr1,arr2),axis=1))  # axis=1 means concatenate column wise i,e to concatenate the arrays columns wise, the count of rows must match

# [[11 22 55]
#  [33 44 66]]

[1 2 3 4 5 6 7 8]
[1. 2. 3. 4. 5. 6. 7. 8.]
[[11 22 33 44]
 [55 66 77 88]]
[[11 22 55]
 [33 44 66]]


In [22]:
# Concatenate

a=np.array([[11,12],[13,14]])
b=np.array([[15,16]])

print(np.concatenate((a,b),axis=0)) # Here axis=0 i,e the array will be concatenate by rows so column count must match.


[[11 12]
 [13 14]
 [15 16]]


In [23]:
# Filter

arr=np.arange(0,20)

print(arr)

# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

print(arr>8)

# [False False False False False False False False False  True  True  True
#   True  True  True  True  True  True  True  True]

print(arr[arr>8]) # filtering based on the condition

# [ 9 10 11 12 13 14 15 16 17 18 19]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True]
[ 9 10 11 12 13 14 15 16 17 18 19]


In [24]:
# extract

# Return the elements of an array that satisfy some condition.( It is also works same as the filter)

arr=np.arange(0,20)

print(arr)

# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

print(np.extract(arr>8,arr)) # It will extract the data directly  without providing the bool values

# [ 9 10 11 12 13 14 15 16 17 18 19]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 9 10 11 12 13 14 15 16 17 18 19]


In [25]:
# count_nonzero

arr= np.array([11,12,13,0,5,443,0,34,0,0,234])

print(np.count_nonzero(arr)) # It will provide the count of non-zero elements

# 7

arr1= np.array([[11,12,0,14],[0,16,0,18],[19,20,0,22],[23,0,25,26]])

print(arr1)

# [[11 12  0 14]
#  [ 0 16  0 18]
#  [19 20  0 22]
#  [23  0 25 26]]

print(np.count_nonzero(arr1))

#11

7
[[11 12  0 14]
 [ 0 16  0 18]
 [19 20  0 22]
 [23  0 25 26]]
11


In [26]:
# nonzero

# Return the indices of the elements that are non-zero.

arr= np.array([11,12,13,0,5,443,0,34,0,0,234])

print(np.nonzero(arr)) # Return the indices of the elements that are non-zero.

# (array([ 0,  1,  2,  4,  5,  7, 10], dtype=int64),) -->3rd,6th,8th,9th index is 0 so it is not shown in the output array

arr1= np.array([[11,12,0,14],[0,16,0,18],[19,20,0,22],[23,0,25,26]])

print(arr1)

# [[11 12  0 14]
#  [ 0 16  0 18]
#  [19 20  0 22]
#  [23  0 25 26]]

print(np.nonzero(arr1)) # it will provide the row and column indices

# (array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 3, 1, 3, 0, 1, 3, 0, 2, 3], dtype=int64))

(array([ 0,  1,  2,  4,  5,  7, 10], dtype=int64),)
[[11 12  0 14]
 [ 0 16  0 18]
 [19 20  0 22]
 [23  0 25 26]]
(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 3, 1, 3, 0, 1, 3, 0, 2, 3], dtype=int64))


In [27]:
# vstack

# Stack arrays in sequence vertically (row wise).

arr1= np.array([1,2,3,4])
arr2= np.array([11,12,13,14])

print(np.vstack((arr1,arr2)))

# [[ 1  2  3  4]
#  [11 12 13 14]]

arr1= np.array([[1,2,3,4]])
arr2= np.array([[11,12,13,14]])

print(np.vstack((arr1,arr2)))

# [[ 1  2  3  4]
#  [11 12 13 14]]

arr1= np.array([[11,12],[13,14]])
arr2= np.array([[15,16]])

print(np.vstack((arr1,arr2))) # here we stacking the content so count of column of arr2 should match with arr1

# [[11 12]
#  [13 14]
#  [15 16]]

[[ 1  2  3  4]
 [11 12 13 14]]
[[ 1  2  3  4]
 [11 12 13 14]]
[[11 12]
 [13 14]
 [15 16]]


In [28]:
#hstack

# Stack arrays in sequence horizontally (column wise).


arr1= np.array([1,2,3,4])
arr2= np.array([11,12,13,14])

print(np.hstack((arr1,arr2)))

# [ 1  2  3  4 11 12 13 14]

arr1= np.array([[11,12],[13,14]])
arr2= np.array([[15,16],[17,18]])

print(np.hstack((arr1,arr2))) # as we are stacking the arrays column wise, the no. of rows of arr1 and arr2 shpuld match else we will get error

[ 1  2  3  4 11 12 13 14]
[[11 12 15 16]
 [13 14 17 18]]


In [29]:
# sum

arr=np.array([11,12,13,14])

print(np.sum(arr))

# or

# print(arr.sum())

# for 2D arrays

arr= np.array([[1,2,3,4],[10,12,11,1],[1,3,2,1]])

print(arr)

# [[ 1  2  3  4]
#  [10 12 11  1]
#  [ 1  3  2  1]]

print(np.sum(arr,axis=0)) #axis=0 means row wise addition will performed like( 1st element from every row will added, 2nd element.....)

# arr.sum(axis=0) 

# [12 17 16  6]

print(np.sum(arr,axis=1)) #axis=1 means column wise addition will performed like( 1st element from every column will added, 2nd element.....)

# arr.sum(axis=1) 

# [10 34  7]

50
[[ 1  2  3  4]
 [10 12 11  1]
 [ 1  3  2  1]]
[12 17 16  6]
[10 34  7]


In [30]:
# finding max element of array

arr1=np.array([1,2,5,22,33,44,2,1,3,889,33,23,4])

# print(arr1.max())
#889

#or

print(np.max(arr1))

#889

arr=np.array([[12,33,45],[10,54,90],[2,89,38]])

print(arr)

# [[12 33 45]
#  [10 54 90]
#  [ 2 89 38]]

print(np.max(arr)) # or arr.max()

#90

print(np.max(arr,axis=0)) # or arr.max(axis=0)

# [12 89 90]

print(np.max(arr,axis=1)) # or arr.max(axis=1)

# [45 90 89]

889
[[12 33 45]
 [10 54 90]
 [ 2 89 38]]
90
[12 89 90]
[45 90 89]


In [31]:
# finding min element of array

arr1=np.array([1,2,5,22,33,44,2,1,3,889,33,23,4])

# print(arr1.min())
#1

#or

print(np.min(arr1))

# 1

arr=np.array([[12,33,45],[10,54,90],[2,89,38]])

print(arr)

# [[12 33 45]
#  [10 54 90]
#  [ 2 89 38]]

print(np.min(arr)) # or arr.min()

# 2

print(np.min(arr,axis=0)) # or arr.min(axis=0)

# [ 2 33 38]

print(np.min(arr,axis=1)) # or arr.min(axis=1)

# [12 10  2]

1
[[12 33 45]
 [10 54 90]
 [ 2 89 38]]
2
[ 2 33 38]
[12 10  2]


In [32]:
# product

# finding product of array

arr1=np.array([1,2,3,1,2,10])

# print(arr1.prod())

#or

print(np.product(arr1))

# 120

arr=np.array([[2,3,4],[10,5,1],[2,4,3]])

print(arr)

# [[ 2  3  4]
#  [10  5  1]
#  [ 2  4  3]]

print(np.product(arr)) # or arr.prod()

# 28800 --> 2*3*4*10*5*1*2*4*3

print(np.product(arr,axis=0)) # or arr.prod(axis=0)

# [40 60 12]

print(np.product(arr,axis=1)) # or arr.prod(axis=1)

# [24 50 24]

120
[[ 2  3  4]
 [10  5  1]
 [ 2  4  3]]
28800
[40 60 12]
[24 50 24]


In [33]:
# Unique

# Find the unique elements of an array.

# Returns the sorted unique elements of an array

arr=np.array([1,2,3,2,1,2,4,5,5,6,5,7,7,8,9,10,11])

print(np.unique(arr))

# [ 1  2  3  4  5  6  7  8  9 10 11]

# we can return the indices as well

print(np.unique(arr,return_index=True))

# (array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([ 0,  1,  2,  6,  7,  9, 11, 13, 14, 15, 16], dtype=int64))

arr1=np.array([[11,12,13,14],[15,16,17,18],[11,12,13,14],[15,16,17,18]])

print(np.unique(arr1))

# [11 12 13 14 15 16 17 18]

# working with axis:

print(np.unique(arr1,axis=0)) # unique rows will be returned 

# [[11 12 13 14]
#  [15 16 17 18]]

print(np.unique(arr1,axis=1)) # unique columns will be returned

# [[11 12 13 14]
#  [15 16 17 18]
#  [11 12 13 14]
#  [15 16 17 18]]

[ 1  2  3  4  5  6  7  8  9 10 11]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([ 0,  1,  2,  6,  7,  9, 11, 13, 14, 15, 16], dtype=int64))
[11 12 13 14 15 16 17 18]
[[11 12 13 14]
 [15 16 17 18]]
[[11 12 13 14]
 [15 16 17 18]
 [11 12 13 14]
 [15 16 17 18]]


In [34]:
# counts using unique function

arr1=np.array([[11,12,13,14],[15,16,17,18],[11,12,13,14],[15,16,17,18]])

print(np.unique(arr1,return_counts=True))

# (array([11, 12, 13, 14, 15, 16, 17, 18]), array([2, 2, 2, 2, 2, 2, 2, 2], dtype=int64))

uniq_ele, count_ele=np.unique(arr1,return_counts=True)

print("unique elements:",uniq_ele)

# unique elements: [11 12 13 14 15 16 17 18]

print("count of elements:",count_ele)

# count of elements: [2 2 2 2 2 2 2 2]

(array([11, 12, 13, 14, 15, 16, 17, 18]), array([2, 2, 2, 2, 2, 2, 2, 2], dtype=int64))
unique elements: [11 12 13 14 15 16 17 18]
count of elements: [2 2 2 2 2 2 2 2]


In [35]:
# Transposing the array

arr1=np.array([[11,12,13,14],[15,16,17,18],[11,12,13,14],[15,16,17,18]])

print("arr1:\n",arr1)

# arr1:
#  [[11 12 13 14]
#  [15 16 17 18]
#  [11 12 13 14]
#  [15 16 17 18]]

print(arr1.T) # arr1 will be transposed ( rows will be converted into columns and col will be converted into rows)

# [[11 15 11 15]
#  [12 16 12 16]
#  [13 17 13 17]
#  [14 18 14 18]]

# we can also perform transpose operation as 

print(arr1.transpose())

# [[11 15 11 15]
#  [12 16 12 16]
#  [13 17 13 17]
#  [14 18 14 18]]

arr1:
 [[11 12 13 14]
 [15 16 17 18]
 [11 12 13 14]
 [15 16 17 18]]
[[11 15 11 15]
 [12 16 12 16]
 [13 17 13 17]
 [14 18 14 18]]
[[11 15 11 15]
 [12 16 12 16]
 [13 17 13 17]
 [14 18 14 18]]


In [36]:
# Reversing an array

# flip

# Reverse the order of elements in an array along the given axis.

# The shape of the array is preserved, but the elements are reordered.

arr= np.array([1,2,3,4,5,6,7,8,9])

print(np.flip(arr))

# for 2D array


arr1=np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22],[23,24,25,26]])

print(arr1)

# [[11 12 13 14]
#  [15 16 17 18]
#  [19 20 21 22]
#  [23 24 25 26]]

print(np.flip(arr1,axis=0)) # axis=0, every 1st element from every row will be taken into consideration and the data will be flipped

                           # again every 2nd element from every row will be taken into consideration and the data will be flipped , process continues
# [[23 24 25 26]
#  [19 20 21 22]
#  [15 16 17 18]
#  [11 12 13 14]]

print(np.flip(arr1,axis=1)) # axis=0, every 1st element from every column will be taken into consideration and the data will be flipped

                           # again every 2nd element from every column will be taken into consideration and the data will be flipped , process continues

# [[14 13 12 11]
#  [18 17 16 15]
#  [22 21 20 19]
#  [26 25 24 23]]

[9 8 7 6 5 4 3 2 1]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]
[[23 24 25 26]
 [19 20 21 22]
 [15 16 17 18]
 [11 12 13 14]]
[[14 13 12 11]
 [18 17 16 15]
 [22 21 20 19]
 [26 25 24 23]]


In [37]:
# flatten and ravel

#  flatten

# when we use flatten function to flatten the array, if we did any changes to our flatten array it will not change the parent array.

arr= np.array([[11,12,13,14],[15,16,17,18]])

print(arr)

# [[11 12 13 14]
#  [15 16 17 18]]

print(arr.flatten())

# [11 12 13 14 15 16 17 18]

flat_arr= arr.flatten()

flat_arr[0]=1000

print(arr) # No change occured to the parent array after making changes in flattend array

# [[11 12 13 14]
#  [15 16 17 18]]


#**********************************************************************************************************************

#Ravel

# when we use ravel function to flatten the array, if we did any changes to our flatten array it will change (effect) the parent array.

arr= np.array([[11,12,13,14],[15,16,17,18]])

print(arr)

# [[11 12 13 14]
#  [15 16 17 18]]

print(arr.ravel())

# [11 12 13 14 15 16 17 18]

flat_arr= arr.ravel()

flat_arr[0]=1000

print(arr) # changes occured to the parent array after making changes in flattend array

# [[1000   12   13   14]
#  [  15   16   17   18]]

[[11 12 13 14]
 [15 16 17 18]]
[11 12 13 14 15 16 17 18]
[[11 12 13 14]
 [15 16 17 18]]
[[11 12 13 14]
 [15 16 17 18]]
[11 12 13 14 15 16 17 18]
[[1000   12   13   14]
 [  15   16   17   18]]


In [38]:
# Converting 1D array to 2D array

arr=np.array([11,12,13,14,15])

print(arr.shape)

print(arr.ndim)

# making arr as 2 dimension using expand_dims

arr1=np.expand_dims(arr,axis=1)

print(arr1.shape) # (5, 1)

print(arr1.ndim) # 2

arr2=np.expand_dims(arr,axis=0)

print(arr2.shape) # (1, 5)
print(arr2.ndim) # 2

(5,)
1
(5, 1)
2
(1, 5)
2


In [39]:
# Rounding

# Evenly round to the given number of decimals.

arr=np.array([0.75,0.9,2.5,3.1])

print(np.round(arr))

# [1. 1. 2. 3.]

print(np.round(arr,decimals=1)) # rounded upto one decimal point

# [0.8 0.9 2.5 3.1]

#***********************************************************************************************************************

arr1=np.array([[11.4,12.4,0.75,1.4],[44.5,30.7,29.6,32.8]])

print(arr1)

# [[11.4  12.4   0.75  1.4 ]
#  [44.5  30.7  29.6  32.8 ]]

print(np.round(arr1))

# [[11. 12.  1.  1.]
#  [44. 31. 30. 33.]]

print(np.round(arr1,decimals=1))

# [[11.4 12.4  0.8  1.4]
#  [44.5 30.7 29.6 32.8]]

[1. 1. 2. 3.]
[0.8 0.9 2.5 3.1]
[[11.4  12.4   0.75  1.4 ]
 [44.5  30.7  29.6  32.8 ]]
[[11. 12.  1.  1.]
 [44. 31. 30. 33.]]
[[11.4 12.4  0.8  1.4]
 [44.5 30.7 29.6 32.8]]


In [40]:
# less and greater

# less

# Return the truth value of (x1 < x2) element-wise.

a= np.array([[11,22,33,44],[55,66,77,88]])
b= np.array([[11,29,66,44],[21,66,65,88]])

print(a)

# [[11 22 33 44]
#  [55 66 77 88]]

print(b)

# [[11 29 66 44]
#  [21 66 65 88]]

print(np.less(a,b))

# [[False  True  True False]
#  [False False False False]]

less= np.less(a,b)

print(a[less])

# [22 33]

[[11 22 33 44]
 [55 66 77 88]]
[[11 29 66 44]
 [21 66 65 88]]
[[False  True  True False]
 [False False False False]]
[22 33]


In [41]:
# Greater

# Return the truth value of (x1 > x2) element-wise.

a= np.array([[11,22,33,44],[55,66,77,88]])
b= np.array([[11,29,66,44],[21,66,65,88]])

print(a)

# [[11 22 33 44]
#  [55 66 77 88]]

print(b)

# [[11 29 66 44]
#  [21 66 65 88]]

print(np.greater(a,b))

# [[False False False False]
#  [ True False  True False]]

greater= np.greater(a,b)

print(a[greater])

# [55 77]

[[11 22 33 44]
 [55 66 77 88]]
[[11 29 66 44]
 [21 66 65 88]]
[[False False False False]
 [ True False  True False]]
[55 77]


In [42]:
# Greater equal

# Return the truth value of (x1 >= x2) element-wise.

a= np.array([[11,22,33,44],[55,66,77,88]])
b= np.array([[11,29,66,44],[21,66,65,88]])

print(a)

# [[11 22 33 44]
#  [55 66 77 88]]

print(b)

# [[11 29 66 44]
#  [21 66 65 88]]

print(np.greater_equal(a,b))

# [[ True False False  True]
#  [ True  True  True  True]]

great_e= np.greater_equal(a,b)

print(a[great_e])

# [11 44 55 66 77 88]

[[11 22 33 44]
 [55 66 77 88]]
[[11 29 66 44]
 [21 66 65 88]]
[[ True False False  True]
 [ True  True  True  True]]
[11 44 55 66 77 88]


In [43]:
# cumulative sum

# Return the cumulative sum of the elements along a given axis.

arr=np.array([10,11,10,1,2,3])

print(np.cumsum(arr)) # [10 21 31 32 34 37]


arr1= np.array([[1,2,3,4,5],[6,4,5,10,11]])

print(np.cumsum(arr1,axis=0))

# [[ 1  2  3  4  5]
#  [ 7  6  8 14 16]]

print(np.cumsum(arr1,axis=1))

# [[ 1  3  6 10 15]
#  [ 6 10 15 25 36]]

#IMPORTANT

# we use same concept for np.cumprod and np.cumproduct as well

[10 21 31 32 34 37]
[[ 1  2  3  4  5]
 [ 7  6  8 14 16]]
[[ 1  3  6 10 15]
 [ 6 10 15 25 36]]


In [44]:
# argmin and argmax

#argmin is used to find the index of the min element 

arr= np.array([1,2,3,2,0,4,100])

print(np.argmin(arr)) # index of 0 is 4

print(np.argmax(arr)) # index of large element 100 is 6.

#******************************************************************************************************************************

arr1=np.array([[10,11,22,1],[45,435,0,90],[89,67,45,1]])

print(arr1)

# [[ 10  11  22   1]
#  [ 45 435   0  90]
#  [ 89  67  45   1]]

print(np.argmin(arr1,axis=0))

# [0 0 1 0]

print(np.argmin(arr1,axis=1))

# [3 2 3]

print(np.argmax(arr1,axis=0))

# [2 1 2 1]

print(np.argmax(arr1,axis=1))

# [2 1 0]

4
6
[[ 10  11  22   1]
 [ 45 435   0  90]
 [ 89  67  45   1]]
[0 0 1 0]
[3 2 3]
[2 1 2 1]
[2 1 0]


In [45]:
# Splitting arrays

# Split an array into multiple sub-arrays as views into `ary`.

arr=np.array([11,12,13,14,15,16])

print(np.split(arr,2))

# [array([11, 12, 13]), array([14, 15, 16])]

print(np.split(arr,[1,4])) # 1st index to 3rd index will be consider as one array, left and right side list will become seperate array's

# [array([11]), array([12, 13, 14]), array([15, 16])]

[array([11, 12, 13]), array([14, 15, 16])]
[array([11]), array([12, 13, 14]), array([15, 16])]


In [46]:
#hsplit

# It is a special case of split() function where axis=1 indicating a horizontal split regardless of the dimension of the input array

arr= np.arange(16).reshape(4,4)

print(arr)

# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]

print(np.hsplit(arr,2)) # it will split the array column wise and divide the colummns into 2 eaual parts, Here we have 4 columns so we can divide as 2 columms + 2 columns

# [array([[ 0,  1],
#        [ 4,  5],
#        [ 8,  9],
#        [12, 13]]), array([[ 2,  3],
#        [ 6,  7],
#        [10, 11],
#        [14, 15]])]

print(np.hsplit(arr,4))

# [array([[ 0],
#        [ 4],
#        [ 8],
#        [12]]), array([[ 1],
#        [ 5],
#        [ 9],
#        [13]]), array([[ 2],
#        [ 6],
#        [10],
#        [14]]), array([[ 3],
#        [ 7],
#        [11],
#        [15]])]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [47]:
# vsplit

# It is a function where axis=0 indicating a vertical split regardless of the dimension of the input array

arr1=np.array([[10,11,22,1],[45,435,0,90],[89,67,45,1]])

print(np.vsplit(arr1,3)) # It will convert the whole array into 3 equal arrays (row splitting)

arr1=np.array([[10,11,22,1],[45,435,0,90],[89,67,45,1],[100,101,102,103]])

# print(np.vsplit(arr1,3)) # we will get error because of arr1 has 4 rows , but in condition we gave 3, we can't divide 4 rows as 3 equal arrays

print(np.vsplit(arr1,4))

# [array([[10, 11, 22,  1]]), array([[ 45, 435,   0,  90]]), array([[89, 67, 45,  1]]), array([[100, 101, 102, 103]])]

print(np.vsplit(arr1,2)) # here we have 4 rows , but we gave condition to convert 4 rows as 2 equal rows( its possible 2 rows+ 2 rows)

# [array([[ 10,  11,  22,   1],
#        [ 45, 435,   0,  90]]), array([[ 89,  67,  45,   1],
#        [100, 101, 102, 103]])]

[array([[10, 11, 22,  1]]), array([[ 45, 435,   0,  90]]), array([[89, 67, 45,  1]])]
[array([[10, 11, 22,  1]]), array([[ 45, 435,   0,  90]]), array([[89, 67, 45,  1]]), array([[100, 101, 102, 103]])]
[array([[ 10,  11,  22,   1],
       [ 45, 435,   0,  90]]), array([[ 89,  67,  45,   1],
       [100, 101, 102, 103]])]


In [48]:
# resize

arr= np.array([[1,2,3],[4,5,6]])

print(arr)

# [[1 2 3]
#  [4 5 6]]

print(np.resize(arr,(3,2)))

# [[1 2]
#  [3 4]
#  [5 6]]

print(np.resize(arr,(3,3))) # size of array won't matters the content will repeat from the initial element to fill the extra elemets

# [[1 2 3]
#  [4 5 6]
#  [1 2 3]]

print(np.resize(arr,(5,5)))

# [[1 2 3 4 5]
#  [6 1 2 3 4]
#  [5 6 1 2 3]
#  [4 5 6 1 2]
#  [3 4 5 6 1]]

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]
 [4 5 6 1 2]
 [3 4 5 6 1]]


In [49]:
# Append

arr=np.array([10,20,30,40])

print(np.append(arr,[100,200,300]))

arr1=np.append(arr,[100,200,300])

print(arr) # content in parent array won't change 

#**************************************************************************************************************

# 2D array

arr= np.array([[10,20,30,40],[50,60,70,80]])

print(arr)

# [[10 20 30 40]
#  [50 60 70 80]]

print(np.append(arr,[[90,100,110,120]])) # If we didn't specify any axis then it append the content by flatten the array

print(np.append(arr,[[90,100,110,120]],axis=0)) # To append the content to row , the count of columns should match.

# [[ 10  20  30  40]
#  [ 50  60  70  80]
#  [ 90 100 110 120]]

print(np.append(arr,[[999],[998]],axis=1)) # To append the content to column the count of rows needs to match

# [[ 10  20  30  40 999]
#  [ 50  60  70  80 998]]


[ 10  20  30  40 100 200 300]
[10 20 30 40]
[[10 20 30 40]
 [50 60 70 80]]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[ 10  20  30  40 999]
 [ 50  60  70  80 998]]


In [50]:
# insert

# numpy.insert(arr, obj, values, axis)

# obj --> the index before which insertion is to be made

# values --> the array of values that needs to be inserted

arr=np.array([10,20,30,40])

print(np.insert(arr,2,[200,400,500]))

# [ 10,  20, 200, 400, 500,  30,  40]

#****************************************************************************************

arr= np.array([[10,20,30,40],[50,60,70,80],[1,2,3,4]])

print(arr)

# [[10 20 30 40]
#  [50 60 70 80]
#  [ 1  2  3  4]]

print(np.insert(arr,1,[1000,2000,3000,4000],axis=0)) # inserted at 1st index (the column count must match for the passing row)

# [[  10   20   30   40]
#  [1000 2000 3000 4000]
#  [  50   60   70   80]
#  [   1    2    3    4]]

print(np.insert(arr,2,[999,998,997],axis=1))  # inserted at 2nd index (the row count must match for the passing column elements)

# [[ 10  20 999  30  40]
#  [ 50  60 998  70  80]
#  [  1   2 997   3   4]]

print(np.insert(arr,2,[[100],[200],[300]],axis=1))

# [[ 10  20 100 200 300  30  40]
#  [ 50  60 100 200 300  70  80]
#  [  1   2 100 200 300   3   4]]

[ 10  20 200 400 500  30  40]
[[10 20 30 40]
 [50 60 70 80]
 [ 1  2  3  4]]
[[  10   20   30   40]
 [1000 2000 3000 4000]
 [  50   60   70   80]
 [   1    2    3    4]]
[[ 10  20 999  30  40]
 [ 50  60 998  70  80]
 [  1   2 997   3   4]]
[[ 10  20 100 200 300  30  40]
 [ 50  60 100 200 300  70  80]
 [  1   2 100 200 300   3   4]]
