In [1]:
import numpy as np

In [2]:
list(range(0,5)) 

# If we want to create the list of 5 numbers starting from 0, then we create like this and in arrays we use function np.arange()

list(range(0.5,1.0)) # using range function we can't generate the list using float values.

TypeError: 'float' object cannot be interpreted as an integer

In [3]:
print(np.arange(0,10))#[0 1 2 3 4 5 6 7 8 9] # This will create the array with the range 0 to 5.

#arange() function is used to generate the sequence of numbers 

print(np.arange(0,10,2)) # [0 2 4 6 8]

# we can generate the float numbers as well using arange function

print(np.arange(0.1,10.0,0.1))

# [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
#  1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6
#  3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4
#  5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2
#  7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.
#  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]

# we can convert the arange array into the list as well using the typecasting

print(list(np.arange(0.1,10.0,0.1)))

# [0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2000000000000002, 1.3000000000000003,
# 1.4000000000000001, 1.5000000000000002, 1.6, 1.7000000000000002, 1.8000000000000003, 1.9000000000000001, 2.0, 2.1, 2.2, 
# 2.3000000000000003, 2.4000000000000004, 2.5000000000000004, 2.6, 2.7, 2.8000000000000003, 2.9000000000000004, 3.0000000000000004,
# 3.1, 3.2, 3.3000000000000003, 3.4000000000000004, 3.5000000000000004, 3.6, 3.7, 3.8000000000000003, 3.9000000000000004, 4.0, 
# 4.1, 4.2, 4.3, 4.3999999999999995, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3,
# 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9,
# 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.700000000000001, 9.8, 9.9]

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6
 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4
 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2
 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.
 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000001, 1.5000000000000002, 1.6, 1.7000000000000002, 1.8000000000000003, 1.9000000000000001, 2.0, 2.1, 2.2, 2.3000000000000003, 2.4000000000000004, 2.5000000000000004, 2.6, 2.7, 2.8000000000000003, 2.9000000000000004, 3.0000000000000004, 3.1, 3.2, 3.3000000000000003, 3.4000000000000004, 3.5000000000000004, 3.6, 3.7, 3.8000000000000003, 3.9000000000000004, 4.0, 4.1, 4.2, 4.3, 4.3999999999999995, 4.5, 4.6, 4.7, 4.8, 4.9, 5.

In [4]:
#reshape

# reshape function is used to change the shape of the given array

arr=np.arange(0,10) #[0 1 2 3 4 5 6 7 8 9]

# If you want to make the above array as 2 rows and 5 columns then you can change (2*5=10 --> size must match with the no.of elements(arr.size))

reshape_arr=arr.reshape(2,5)

print(reshape_arr)

# [[0 1 2 3 4]
#  [5 6 7 8 9]]

reshape=arr.reshape(5,-1) # here we can provide -1 or any negative number to column so that python understand that 
                          # it will be 2, according to shape and size of array
#reshape=arr.reshape(5,-1000000000000000000000000) # it is also works as above function only (negative value can be anything)
print(reshape)

# [[0 1]
#  [2 3]
#  [4 5]
#  [6 7]
#  [8 9]]

reshape=arr.reshape(-1,10) # Here we can provide -1 to rows as well so that python automatically caluculate the row count according to column

print(reshape)

# [[0 1 2 3 4 5 6 7 8 9]]

#******************************************************************************************************************

arr= np.arange(0,12).reshape(3,4)

print(arr,arr.shape) # shape is (3,4)

# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

reshape= arr.reshape(2,2,3) # It will create the 3D array ( 2*2*3==12 --> matches with the size of array so it worked)

print(reshape) 

# [[[ 0  1  2]
#   [ 3  4  5]]

#  [[ 6  7  8]
#   [ 9 10 11]]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
# np.linspace() is used to generate the sequence of numbers with the specified limit

# syntax: np.linspace(start,end,into how many equal parts you want to divide)
# by defaultly the value of "into how many equal parts you want to divide" is 50.

print(np.linspace(0,10))

# Output:
    
#     array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
#         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
#         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
#         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
#         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
#         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
#         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
#         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
#         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
#         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

print(np.linspace(0,10,10)) # Here the values from 0 to 10 will be divided into 10 equal parts

# Output:
#     [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
#   6.66666667  7.77777778  8.88888889 10.        ]

print(np.linspace(0,11,12))

# [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [6]:
# np.logspace

# logspace is used to generate the logarathmic values for the given ranage of values
# Return numbers spaced evenly on a log scale.

print(np.logspace(0,10,10))  #np.logspace(start,stop,num,base...) # by default base=10 num=50

# [1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
#  2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
#  7.74263683e+08 1.00000000e+10]

print(np.logspace(0,10,10,base=2))

# [1.00000000e+00 2.16011948e+00 4.66611616e+00 1.00793684e+01
#  2.17726400e+01 4.70315038e+01 1.01593667e+02 2.19454460e+02
#  4.74047853e+02 1.02400000e+03]

print(np.logspace(1,5,10,base=2))

# [ 2.          2.72158     3.70349885  5.0396842   6.85795186  9.33223232
#  12.69920842 17.28095582 23.51575188 32.        ]

[1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
 2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
 7.74263683e+08 1.00000000e+10]
[1.00000000e+00 2.16011948e+00 4.66611616e+00 1.00793684e+01
 2.17726400e+01 4.70315038e+01 1.01593667e+02 2.19454460e+02
 4.74047853e+02 1.02400000e+03]
[ 2.          2.72158     3.70349885  5.0396842   6.85795186  9.33223232
 12.69920842 17.28095582 23.51575188 32.        ]


In [7]:
# Generating the array of zeros with the specified rows and columns

print(np.zeros(4)) # If columns not specified then it will generate the array of zeros with the specified size

# [0. 0. 0. 0.]

print(np.zeros((5,6)))

# [[0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]]

print(np.zeros((5,7),dtype=int)) # we can provide the data type as well

# [[0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0]]

print(np.zeros((3,2,3),dtype=int)) # It will create the 3 d array with 2 rows and columns 

# [[[0 0 0]
#   [0 0 0]]

#  [[0 0 0]
#   [0 0 0]]

#  [[0 0 0]
#   [0 0 0]]]

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [8]:
# zeros_like

# np.zeros_like function is used to generate the array of zeros as like a shape of another array

arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape) #(2, 4)

# If you want to generate the zeros like the arr array then we use np.zeros_like

print(np.zeros_like(arr))

# [[0 0 0 0]
#  [0 0 0 0]]

zers_arr=np.zeros_like(arr)

print(zers_arr.shape)

(2, 4)
[[0 0 0 0]
 [0 0 0 0]]
(2, 4)


In [9]:
# Array of 1's 

np.ones(4) # as there is no column specified it will generate the array of 1's for 4 elements

# array([1., 1., 1., 1.])

print(np.ones((6,7))) # we can generate the array of 1's using the specified rows and columns

# [[1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1.]]


print(np.ones((6,7),dtype=int)) # we can generate the array of 1's using the specified rows and columns and datatype as int as well

# [[1 1 1 1 1 1 1]
#  [1 1 1 1 1 1 1]
#  [1 1 1 1 1 1 1]
#  [1 1 1 1 1 1 1]
#  [1 1 1 1 1 1 1]
#  [1 1 1 1 1 1 1]]

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [10]:
# empty array

# Return a new array of given shape and type, without initializing entries.

print(np.empty((3,4)))

# [[ 0.  1.  2.  3.]
#  [ 4.  5.  6.  7.]
#  [ 8.  9. 10. 11.]]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [11]:
# np.identity()

# it is used to generate the identity matrix as a square matrix ( no.of rows == no.of columns)
# Return the identity array.

print(np.identity(3))#as we know for identity matrix the rows and columns is equal so we need to initialize one value, In this case it is 3

# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

print(np.identity(4,dtype=int))

# [[1 0 0 0]
#  [0 1 0 0]
#  [0 0 1 0]
#  [0 0 0 1]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
# np.eye()

# It is also used to generate the identity matrix but here we can specify the rows and columns
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

print(np.eye(5)) # 

# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 1.]]

print(np.eye(5,dtype=int))

# [[1 0 0 0 0]
#  [0 1 0 0 0]
#  [0 0 1 0 0]
#  [0 0 0 1 0]
#  [0 0 0 0 1]]

print(np.eye(3,5,dtype=int)) # Here we have generated the matrix with diagonal element as 1 and remaining elements as 0.

# [[1 0 0 0 0]
#  [0 1 0 0 0]
#  [0 0 1 0 0]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [13]:
# Generating the array with random values 

print(np.random.rand(2,3))

# [[-0.91793979 -1.40786569  0.44719101]
#  [ 0.06297761 -0.97749834 -0.50261376]]

# Here for the generated data the mean can be anything and standard deviation can be anything 

[[0.67227158 0.29898275 0.49456555]
 [0.1215553  0.82482372 0.38504152]]


In [14]:
# IMPORTANT, we use this most in the statistic class to generate the data for standard normal distribution

# Generating the array with random values which follows standard normal distribution (mean=0 standard deviation=1)

print(np.random.randn(2,3)) # Here the generated data follows standard normal distribution with mean=0 standard deviation=1

# [[1.20732879 1.63218093 0.04569626]
#  [2.0863611  1.61733634 0.05816859]]

[[-0.30071923  0.5295019   0.13617307]
 [ 1.80897819 -0.0282487   0.15272252]]


In [15]:
# we can generate the array with random integer numbers within specified limit and in given shape

print(np.random.randint(1,5,(5,6))) # It will generate the array with shape (5,6) and the values in array in between 1 to 5(excluded)

# [[4 2 2 2 1 3]
#  [4 3 3 2 4 1]
#  [4 3 1 3 1 3]
#  [1 4 4 4 4 1]
#  [2 1 2 4 4 4]]

print(np.random.randint(-1,6,(5,6)))

# [[ 3  0  2  2  0  1]
#  [ 2  1  1  5  2  0]
#  [ 4 -1  3  4  4  4]
#  [ 4  0  1 -1  4  0]
#  [ 5  1 -1  4  1 -1]]

[[4 2 4 4 1 4]
 [1 4 1 3 2 2]
 [2 3 1 4 4 2]
 [2 1 2 3 2 2]
 [1 3 2 2 4 1]]
[[ 0  0  5  2  5  4]
 [-1  2 -1  5 -1  0]
 [-1  0  2 -1  3  5]
 [ 3  0 -1  5 -1  2]
 [ 5 -1  1  4  3  2]]


In [16]:
# filtering the content in the array

arr1= np.random.randint(1,10,(3,4))

print(arr1)

# if you want to filter the values which has >5 then

condition = arr1>5

print(arr1[condition])


[[5 7 1 2]
 [8 5 1 4]
 [1 8 3 6]]
[7 8 8 6]


In [17]:
# Indexing operations on arrays

arr1=np.array([[11,22,33,44],[55,66,77,88],[99,111,222,333]])
print(arr1)

# [[ 11  22  33  44]
#  [ 55  66  77  88]
#  [ 99 111 222 333]]

# we can access the content of the array using indexing.

print(arr1[0]) # [11 22 33 44]

print(arr1[0:2]) # it will fetch the two rows

# [[11 22 33 44]
#  [55 66 77 88]]

print(arr1[0:2,0:3]) # it will fetch the rows from 0th index to 1st index and columns from 0th index to 2nd index

# [[11 22 33]
#  [55 66 77]]

print(arr1[0:2:2,0:3:2]) # here we have specified the step as 2

# here the 0th row and 0th column,2nd column will be selected as per the step condition.

# [[11 33]]

print(arr1[0,[0,1,2]]) # accessing the 0th row and elements from 0th 1st 2nd elements from columns

# [11 22 33]

[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 111 222 333]]
[11 22 33 44]
[[11 22 33 44]
 [55 66 77 88]]
[[11 22 33]
 [55 66 77]]
[[11 33]]
[11 22 33]


In [18]:
#Indexing

arr1= np.arange(10,50).reshape(4,-1)
print(arr1)

# [[10 11 12 13 14 15 16 17 18 19]
#  [20 21 22 23 24 25 26 27 28 29]
#  [30 31 32 33 34 35 36 37 38 39]
#  [40 41 42 43 44 45 46 47 48 49]]

print(arr1[0:2,0:3])

# [[10 11 12]
#  [20 21 22]]

print(arr1[0:4:2,0:6:2])

# [[10 12 14]
#  [30 32 34]]

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[10 11 12]
 [20 21 22]]
[[10 12 14]
 [30 32 34]]


In [19]:
arr1= np.arange(10,50).reshape(4,-1)

print(arr1)

# [[10 11 12 13 14 15 16 17 18 19]
#  [20 21 22 23 24 25 26 27 28 29]
#  [30 31 32 33 34 35 36 37 38 39]
#  [40 41 42 43 44 45 46 47 48 49]]

# If you want to retrieve the below data.

# [[24 25]
#   [34 35]]

print(arr1[1:3,[4,5]]) # extracting the row 1 to 2 and 4th and 5th column

# array([[24, 25],
#        [34, 35]])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[24 25]
 [34 35]]


In [20]:
# addition, subtraction, multiplication and division operation on arrays

# all actions will be performed based on the index wise.

arr1=np.random.randint(1,5,(3,3))

print("arr1:\n",arr1)

arr2=np.random.randint(1,5,(3,3))

print("arr2:\n",arr2)

arr1:
 [[3 2 1]
 [2 2 3]
 [1 2 2]]
arr2:
 [[3 1 3]
 [4 4 1]
 [4 4 2]]


In [21]:
# addition

print(arr1+arr2)

[[6 3 4]
 [6 6 4]
 [5 6 4]]


In [22]:
# subtraction

print(arr1-arr2)

[[ 0  1 -2]
 [-2 -2  2]
 [-3 -2  0]]


In [23]:
#multiplication --> here multiplication is done based on indexes

print(arr1*arr2) # --> * will give you index wise multiplication and @ will give you matrix multiplication (see below)

# matrix multiplication is different than the index multiplication (as we know the theoritical explanation for matrix multiplication)

matrix_arr1= np.matrix(arr1)
matrix_arr2=np.matrix(arr2)

print("matrix 1:\n", matrix_arr1)
print("matrix 2:\n", matrix_arr2)

print("matrix multiplication after converting arrays into matrices:\n",matrix_arr1*matrix_arr2)


# performing matrix multiplication using arrays

print("matrix multiplication using @ symbol and arr1 and arr2:\n",arr1@arr2) # used @ to perform matrix multiplication


[[9 2 3]
 [8 8 3]
 [4 8 4]]
matrix 1:
 [[3 2 1]
 [2 2 3]
 [1 2 2]]
matrix 2:
 [[3 1 3]
 [4 4 1]
 [4 4 2]]
matrix multiplication after converting arrays into matrices:
 [[21 15 13]
 [26 22 14]
 [19 17  9]]
matrix multiplication using @ symbol and arr1 and arr2:
 [[21 15 13]
 [26 22 14]
 [19 17  9]]


In [24]:
# division
print(arr1/arr2)

[[1.         2.         0.33333333]
 [0.5        0.5        3.        ]
 [0.25       0.5        1.        ]]


In [25]:
# modules

print(arr1%arr2)

[[0 0 1]
 [2 2 0]
 [1 2 0]]


In [26]:
print(arr1/0)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\Nethajimahendra K\AppData\Local\Temp\ipykernel_23004\560058255.py:1: RuntimeWarning: divide by zero encountered in divide
  print(arr1/0)


In [27]:
# Numpy broadcasting

arr= np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
arr+5 # here we broadcasting the value 5 

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [29]:
# lets create two arrays 

arr1= np.zeros((3,4)) # shape (3,4)

arr2= np.array([[11,22,33,44]]) # shape (1,4)

print("arr1:\n",arr1,"\n","arr2:\n",arr2)

print("broadcasting the arr1 and arr2:\n",arr1+arr2) # here the data in arr2 is added horizontally (row wise)

# to perform this action the rows or columns must match according to the operation

arr1:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 arr2:
 [[11 22 33 44]]
broadcasting the arr1 and arr2:
 [[11. 22. 33. 44.]
 [11. 22. 33. 44.]
 [11. 22. 33. 44.]]


In [30]:
a=np.zeros((3,4))
b=np.array([[22,33,44]])

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [31]:
print(a+b.T) # b.transpose() also works here, here the shape of array a is (3,4) and shape of b is (1,3)

# to match the row of the array a we have transposed b, now the shape of b is (3,1) and a is (3,4)

# print(b.transpose())
print(b.T, b.T.shape)

# print(a+b.transpose())

[[22. 22. 22. 22.]
 [33. 33. 33. 33.]
 [44. 44. 44. 44.]]
[[22]
 [33]
 [44]] (3, 1)


In [32]:
#square root

arr= np.random.randint(1,50,(3,4))

print(arr)

print("square root:\n",np.sqrt(arr))

# log10 operation

print("log10 operation:\n",np.log10(arr))

# exponential operation

print("exponential operation:\n",np.exp(arr))

# finding mean

print("The mean of arr:\n",np.mean(arr))

# finding max element in array

print("The max element in an arr:\n", np.max(arr))

# finding min element in array

print("The min element in an arr:\n", np.min(arr))

[[28 45 33 37]
 [28 27 13 20]
 [40 30  1 14]]
square root:
 [[5.29150262 6.70820393 5.74456265 6.08276253]
 [5.29150262 5.19615242 3.60555128 4.47213595]
 [6.32455532 5.47722558 1.         3.74165739]]
log10 operation:
 [[1.44715803 1.65321251 1.51851394 1.56820172]
 [1.44715803 1.43136376 1.11394335 1.30103   ]
 [1.60205999 1.47712125 0.         1.14612804]]
exponential operation:
 [[1.44625706e+12 3.49342711e+19 2.14643580e+14 1.17191424e+16]
 [1.44625706e+12 5.32048241e+11 4.42413392e+05 4.85165195e+08]
 [2.35385267e+17 1.06864746e+13 2.71828183e+00 1.20260428e+06]]
The mean of arr:
 26.333333333333332
The max element in an arr:
 45
The min element in an arr:
 1
